CREATE TABLE IF NOT EXISTS FABRICANT(
    COD_FABRICANT NUMERIC(3),
    NOM VARCHAR(15),
    PAIS VARCHAR (15),
    CONSTRAINT PK_FABRICANT PRIMARY KEY (COD_FABRICANT),
    CONSTRAINT NOM_MAJUS CHECK (NOM = UPPER(NOM)),
    CONSTRAINT PAIS_MAJUS CHECK (PAIS = UPPER(PAIS)));

CREATE TABLE IF NOT EXISTS ARTICLE(
    COD_ARTICLE VARCHAR(20),
    COD_FABRICANT NUMERIC(3),
    PES NUMERIC(3),
    CATEGORIA VARCHAR(10),
    PREU_VENDA DECIMAL(6,2),
    PREU_COST DECIMAL(6,2),
    STOCK NUMERIC(5),
    CONSTRAINT PK_ARTICLE PRIMARY KEY (COD_ARTICLE, COD_FABRICANT, PES, CATEGORIA),
    CONSTRAINT FK_COD_FABRICANT FOREIGN KEY (COD_FABRICANT) REFERENCES FABRICANT(COD_FABRICANT),
    CONSTRAINT CK_PREU_VENDA CHECK (PREU_VENDA >0),
    CONSTRAINT CK_PREU_COST CHECK (PREU_COST >0),
    CONSTRAINT CK_PES CHECK (PES >0),
    CONSTRAINT CK_CATEGORIA CHECK (CATEGORIA IN ('Primera', 'Segona', 'Tercera')));
    

