-- Crea un base de dades anomenada empleats
CREATE DATABASE empleats;
-- Crea un usuari anomenat empleats amb la contrasenya 'empleats' i perfil de superusuari
CREATE USER empleats WITH SUPERUSER CREATEROLE ENCRYPTED PASSWORD 'empleats';
-- Assigna l'usuari empleats com a propietari de la BBDD empleats
ALTER DATABASE empleats OWNER TO empleats;
-- Assigna tots els privilegis a l'usuari empleats sobre la BBDD empleats
GRANT ALL PRIVILEGES ON DATABASE empleats TO empleats;

CREATE TABLE IF NOT EXISTS REGION (
COD_REGION NUMERIC NOT NULL, -- ell ha posat NUMERIC(5)
NOMBRE TEXT, -- ell ha posat VARCHAR(40)
CONSTRAINT PK_REGION PRIMARY KEY (COD_REGION));

CREATE TABLE IF NOT EXISTS PROVINCIA(
COD_PROVINCIA NUMERIC NOT NULL, -- ell ha posat NUMERIC(5)
NOMBRE TEXT, -- ell ha posat VARCHAR(40)
COD_REGION NUMERIC, -- ell ha posat NUMERIC(5)
CONSTRAINT PK_PROVINCIA PRIMARY KEY (COD_PROVINCIA),
CONSTRAINT FK_COD_REG FOREIGN KEY (COD_REGION) REFERENCES REGION(COD_REGION)); -- ell ha posat COM A NOM FK_PROV_REG_CODREGION   (FK+nomTaula+nomTaulaForanea+nomAtribut)

CREATE TABLE IF NOT EXISTS LOCALIDAD(
COD_LOCALIDAD NUMERIC NOT NULL,
NOMBRE TEXT,
COD_PROVINCIA NUMERIC,
CONSTRAINT PK_LOCALIDAD PRIMARY KEY (COD_LOCALIDAD),
CONSTRAINT FK_COD_PROV FOREIGN KEY (COD_PROVINCIA) REFERENCES PROVINCIA (COD_PROVINCIA));

CREATE TABLE IF NOT EXISTS EMPLEADO (
ID NUMERIC NOT NULL, --numeric(3)
DNI VARCHAR(9)UNIQUE, -- DNI és sense LLETRA, VARCHAR està bé
NOMBRE TEXT,
FECHA_NAC DATE,
TELEFONO NUMERIC, -- char(9)
SALARIO NUMERIC, -- MUMERIC(6,2) --> 6 enters i 2 decimals
COD_LOCALIDAD NUMERIC, --(5)
CONSTRAINT PK_EMPLEADO PRIMARY KEY (ID),
CONSTRAINT FK_COD_LOC FOREIGN KEY (COD_LOCALIDAD) REFERENCES LOCALIDAD(COD_LOCALIDAD));