CREATE DATABASE proveidors;
CREATE USER proveidors WITH SUPERUSER CREATEROLE ENCRYPTED PASSWORD 'proveidors';
ALTER DATABASE proveidors OWNER TO proveidors;
GRANT ALL PRIVILEGES ON DATABASE proveidors TO proveidors;

CREATE TABLE IF NOT EXISTS FABRICANT(
COD_FABRICANT NUMERIC(3),
NOM VARCHAR(15),
PAIS VARCHAR (15),

    CONSTRAINT PK_FABRICANT PRIMARY KEY (COD_FABRICANT),
    CONSTRAINT NOM_MAJUS CHECK (NOM = UPPER(NOM)),
    CONSTRAINT PAIS_MAJUS CHECK (PAIS = UPPER(PAIS))
);

--Li ha ficat NOT NULL a tots els camps

CREATE TABLE IF NOT EXISTS ARTICLE(
COD_ARTICLE VARCHAR(20),
COD_FABRICANT NUMERIC(3),
PES NUMERIC(3),
CATEGORIA VARCHAR(10),
PREU_VENDA DECIMAL(6,2),
PREU_COST DECIMAL(6,2),
STOCK NUMERIC(5),

    CONSTRAINT PK_ARTICLE PRIMARY KEY (COD_ARTICLE, COD_FABRICANT, PES, CATEGORIA),
    CONSTRAINT FK_COD_FABRICANT FOREIGN KEY (COD_FABRICANT) REFERENCES FABRICANT(COD_FABRICANT),
    CONSTRAINT CK_PREU_VENDA CHECK (PREU_VENDA >0),
    CONSTRAINT CK_PREU_COST CHECK (PREU_COST >0),
    CONSTRAINT CK_PES CHECK (PES >0),
    CONSTRAINT CK_CATEGORIA CHECK (CATEGORIA IN ('Primera', 'Segona', 'Tercera'))

);

--CORRECCIONS  
-- Es pot fer el CHECK de preuVenda, preuCost i altes en una línia, però el Joan prefereix per separat per si ho volem modificar
-- Separa les constrains i fes-li una tabulació
-- Posa el tancament de la taula a una línia a part.
-- );
-- Més info: https://docs.google.com/presentation/d/1r-hXZWLp6z_aXMl97AiiOFVvT_6t8HuUHqNFj5t58aU/edit#slide=id.gb7c51ac3b8_0_3

