CREATE DATABASE cadastre;
CREATE USER cadastre WITH SUPERUSER CREATEROLE ENCRYPTED PASSWORD 'cadastre';
ALTER DATABASE cadastre OWNER TO cadastre;
GRANT ALL PRIVILEGES ON DATABASE cadastre TO cadastre;

psql -U cadastre -W -d cadastre

CREATE TABLE ZONAURBANA(
    NOM_ZONA VARCHAR(60) NOT NULL,

    CONSTRAINT PK_ZONAURBANA PRIMARY KEY (NOM_ZONA),
    CONSTRAINT CK_NOMZONA_MAJUS CHECK (NOM_ZONA = UPPER(NOM_ZONA))
);


CREATE TABLE VIVENDA(
    CARRER VARCHAR(80) NOT NULL,
    NOMBRE NUMERIC(4) NOT NULL,

    TIPUS_VIVENDA VARCHAR(1),
    CODI_POSTAL NUMERIC(5) DEFAULT 00001,
    METRES NUMERIC(5),
    NOM_ZONA VARCHAR(60),

    CONSTRAINT PK_VIVENDA PRIMARY KEY (CARRER,NOMBRE),
    CONSTRAINT FK_VIVENDA_ZONAURBANA_NOMZONA FOREIGN KEY (NOM_ZONA) REFERENCES ZONAURBANA(NOM_ZONA),
    CONSTRAINT CK_CARRER_MAJUS CHECK (CARRER = INITCAP(CARRER)),
    CONSTRAINT CK_NOMBRE CHECK (NOMBRE > 0),
    CONSTRAINT CK_TIPUS_VIVENDA CHECK (TIPUS_VIVENDA IN ('C', 'B'))
);

CREATE TABLE PERSONA(
    DNI VARCHAR(12),
    
    NOM_PERSONA VARCHAR(20) NOT NULL,
    COGNOMS_PERSONA VARCHAR(40) NOT NULL,
    DNI_C VARCHAR(12),
    CARRER VARCHAR(80),
    NOMBRE NUMERIC(4) NOT NULL,

    CONSTRAINT PK_PERSONA PRIMARY KEY (DNI),
    CONSTRAINT FK_PERSONA_VIVENDA_CARRER_NOMBRE FOREIGN KEY (CARRER, NOMBRE) REFERENCES VIVENDA(CARRER, NOMBRE),
    CONSTRAINT FK_PERSONA_DNI_C FOREIGN KEY (DNI_C) REFERENCES PERSONA(DNI)
);

CREATE TABLE BLOCCASES(
    CARRER VARCHAR(80) NOT NULL,
    NOMBRE NUMERIC(4) NOT NULL,

    METRES_B NUMERIC(4),

    CONSTRAINT PK_BLOCCASES PRIMARY KEY (CARRER,NOMBRE),
    CONSTRAINT FK_BLOCCASES_VIVDENDA_CARRER_NOMBRE FOREIGN KEY (CARRER,NOMBRE) REFERENCES VIVENDA(CARRER,NOMBRE) ON DELETE CASCADE,
    CONSTRAINT CK_METRES_B CHECK (METRES_B > 0)
);


CREATE TABLE CASAPARTICULAR(
    CARRER VARCHAR(80) NOT NULL,
    NOMBRE VARCHAR(4) NOT NULL,

    METRES_C NUMERIC(4),
    DNI_CP VARCHAR(12),

    CONSTRAINT PK_CASAPARTICULAR PRIMARY KEY (CARRER,NOMBRE),
    CONSTRAINT FK_CASAPARTICULAR_PERSONA_DNI_CP FOREIGN KEY (DNI_CP) REFERENCES PERSONA(DNI) ON DELETE CASCADE,
    CONSTRAINT CK_METRES_C CHECK (METRES_C > 0)
);

CREATE TABLE PIS(
    CARRER VARCHAR(80) NOT NULL,
    NOMBRE NUMERIC(4) NOT NULL,
    ESCALA VARCHAR(1) NOT NULL,
    PLANTA NUMERIC(2) NOT NULL,
    PORTA VARCHAR(2) NOT NULL,

    METRES_P NUMERIC(4),
    DNI_P VARCHAR(12),

    CONSTRAINT PK_PIS PRIMARY KEY (CARRER,NOMBRE,ESCALA,PLANTA,PORTA),
    CONSTRAINT FK_PIS_PERSONA FOREIGN KEY (DNI_P) REFERENCES PERSONA(DNI) ON DELETE CASCADE,
    CONSTRAINT FK_PIS_BLOCCASES_CARRER_NOMBRE FOREIGN KEY (CARRER,NOMBRE) REFERENCES BLOCCASES(CARRER,NOMBRE) ON DELETE CASCADE,
    CONSTRAINT CK_METRES_P CHECK (METRES_P > 0)    
);

CREATE TABLE HABITAPIS(
    DNI VARCHAR(12) NOT NULL,

    CARRER VARCHAR(80) NOT NULL,
    NOMBRE NUMERIC(4) NOT NULL,
    ESCALA VARCHAR(1) NOT NULL,
    PLANTA NUMERIC(2) NOT NULL,
    PORTA VARCHAR(2) NOT NULL,



    CONSTRAINT PK_HABITAPIS PRIMARY KEY(DNI),
    CONSTRAINT FK_HABITAPIS_PERSONA_DNI FOREIGN KEY (DNI) REFERENCES PERSONA(DNI),
    CONSTRAINT FK_HABITAPIS_PIS FOREIGN KEY (CARRER, NOMBRE, ESCALA, PLANTA, PORTA) REFERENCES PIS(CARRER, NOMBRE, ESCALA, PLANTA,PORTA) ON DELETE CASCADE
);